import type { ServerBuild } from '@remix-run/cloudflare';
import { createPagesFunctionHandler } from '@remix-run/cloudflare-pages';

// use dynamic import to avoid ES modules syntax issues in Cloudflare Workers
export const onRequest = async (context: any) => {
  try {
    // @ts-ignore because the server build file is generated by `remix vite:build`
    const serverBuild = await import('../build/server');
    const handler = createPagesFunctionHandler({
      build: serverBuild as unknown as ServerBuild,
    });

    return handler(context);
  } catch (error) {
    console.error('Error in Cloudflare Pages function:', error);
    return new Response('Server Error', { status: 500 });
  }
};
